### ISSUE TITLE
error with mseed_predictor

### ISSUE THREAD

**Issue by saeedsltm** [smousavi05/EQTransformer#100]
I've got the following error when running EQT using mseed_predictor:

> 11-06 21:25 [INFO] [EQTransformer] Started working on JNAK, 7 out of 36 ...
> 11-06 21:25 [INFO] [EQTransformer] 20200101T000000Z__20200102T000000Z.mseed
> 11-06 21:25 [INFO] [EQTransformer] 20200102T000000Z__20200103T000000Z.mseed
> 11-06 21:25 [INFO] [EQTransformer] 20200103T000000Z__20200104T000000Z.mseed
> 11-06 21:25 [INFO] [EQTransformer] 20200104T000000Z__20200105T000000Z.mseed
> 11-06 21:26 [INFO] [EQTransformer] 20200105T000000Z__20200106T000000Z.mseed
> 11-06 21:26 [INFO] [EQTransformer] 20200106T000000Z__20200107T000000Z.mseed
> 11-06 21:26 [INFO] [EQTransformer] 20200107T000000Z__20200108T000000Z.mseed
> 11-06 21:26 [INFO] [EQTransformer] 20200108T000000Z__20200109T000000Z.mseed
> 11-06 21:26 [INFO] [EQTransformer] 20200109T000000Z__20200110T000000Z.mseed
> 11-06 21:26 [INFO] [EQTransformer] 20200110T000000Z__20200111T000000Z.mseed
> 11-06 21:26 [INFO] [EQTransformer] 20200111T000000Z__20200112T000000Z.mseed
> 11-06 21:26 [INFO] [EQTransformer] 20200112T000000Z__20200113T000000Z.mseed
> 11-06 21:27 [INFO] [EQTransformer] 20200113T000000Z__20200114T000000Z.mseed
> 11-06 21:27 [INFO] [EQTransformer] 20200114T000000Z__20200115T000000Z.mseed
> 11-06 21:27 [INFO] [EQTransformer] 20200115T000000Z__20200116T000000Z.mseed
> Traceback (most recent call last):
>   File "./runEQT.py", line 83, in <module>
>     batch_size=500)
>   File "/home/tatar/Programs/miniconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/core/mseed_predictor.py", line 311, in mseed_predictor
>     predD, predP, predS = model.predict_generator(pred_generator)
> ValueError: not enough values to unpack (expected 3, got 0)
> 

this is occurred for one station and it worked for rest of them.

**Comment by smousavi05** [comment]
@saeedsltm that station might have very short duration of data. Trying smaller batch size might help.

**Comment by saeedsltm** [comment]
@smousavi05 thanks, it worked!
