### ISSUE TITLE
Question -> 2020 paper test set vs. test.npy size discrepancy?

### ISSUE THREAD

**Issue by davidtwomey** [smousavi05/EQTransformer#104]
Hi,
Thanks for providing this codebase open-source!
One quick question -> I am having difficulty matching the number of test traces provided by the `test.npy` here and the 
number of traces in the original paper test set.
Based on the confusion matrix in supplementary Fig. 7, it appears the original test set contained 114,592 samples.
However, the `test.npy` has 126,566.

Are the two sets the same? Can you advise?

Many thanks,

David

**Comment by smousavi05** [comment]
Hi @davidtwomey the test.npy contains some extra noise samples as they were added later to the dataset but missing from the reported values in the paper.
