### ISSUE TITLE
Questions re. training data format

### ISSUE THREAD

**Issue by tomeracles** [smousavi05/EQTransformer#106]
Hi,
First, thanks so much for this cool code. I'm trying to see if I can use transfer learning to fine tune the EQT model on some waveforms that I've picked myself from my study area (several thousand). Naturally, a big issue is to get the metadata into the correct (STEAD) format. I have some quick questions about appropriate waveforms and values to use:

1) Is it possible/advisable to use waveforms where I've picked only P, or only S?
2) How important is the value of coda_end_sample? Does this need to have been picked or can I just make it a certain portion of the waveform after the phase picks?
3) What's the significance of p_weight and s_weight — are they used at all in the training?

Sorry if the answers to these questions are written somewhere, I haven't found them yet.

Many thanks
Tom

**Comment by smousavi05** [comment]
@tomeracles Hi Tom

1. yes you can use the waveforms with only P or S picks
2. coda_end_sample is not used in eqtransformer. As you can see from code a rough estimate of 1.2 X (s_arrival - p_arrival) + P_time is used to mark the earthquake
3. P and S weights are not very important for training. 

You can use QuakeLabeler [https://maihao14.github.io/QuakeLabeler/] or SeisBench [https://github.com/seisbench/seisbench] to labele and convert your data into STEAD format,

Good Luck
