### ISSUE TITLE
station with multiple channels ignored!

### ISSUE THREAD

**Issue by saeedsltm** [smousavi05/EQTransformer#108]
When we have a station with different channel names which working in different time periods (let say BH[ZNE] during 2019-2020 and HH[ZNE] during 2020-2021) the program prepare only one channel in output json file (referring to function makeStationList()) and finally the other channels data will not be downloaded.

**Comment by smousavi05** [comment]
@saeedsltm so is it because only the data under one channel name is available online? The program in EqT is only a wrapper around Obspy so if it doesn't get it might be because the data is not available or is under different name.
