### ISSUE TITLE
EQTransformer training parameters

### ISSUE THREAD

**Issue by alirezaniki** [smousavi05/EQTransformer#111]
Dear Mostafa,

I am going to train EQT on a new dataset in a way in which at last I can compare it with EQT. I've read the paper but I am still not sure about the values for cnn_blocks and lstm_blocks in the test_trainer code. Am I supposed to use the default values? I mean, are those values the ones that EQT has been trained on?

Many thanks,
Alireza.

**Comment by smousavi05** [comment]
Hi @alirezaniki depending on your dataset, the optimal values for the architecture might change. You can use hyperparameter tuning packages to find the optimal values for your case. The default values are those that worked best for STEAD dataset. BTW, you can use those packages like seibench for converting your data into STEAD format and retraining EqT.

**Comment by alirezaniki** [comment]
@smousavi05  Thank you so much for your comments. Actually, my new dataset is derived from STEAD, so I'll try to use and fine-tune the default parameters.
