### ISSUE TITLE
Pakage doesn't run under Windows - invalid filename

### ISSUE THREAD

**Issue by ConstantinGahr** [smousavi05/EQTransformer#112]
Hi,

unfortunately, the package doesn't run under windows.

**How to reproduce:**
- run `examples/detection.ipynb`
- the second cell fails with 
    ```python
    OSError: [Errno 22] Invalid argument: 'C:\\Users\\test\\examples\\detections1\\B921_outputs\\figures\\B921_PB_EH_2019-09-01T00:02:06.008300Z.png'
    ```

**Minimum not working example**
Fails:
```python
from matplotlib import pyplot as plt
import numpy as np

plt.plot(np.arange(10))
plt.savefig('not:work:ing.png')
```
Works:
```python
from matplotlib import pyplot as plt
import numpy as np

plt.plot(np.arange(10))
plt.savefig('work:ing.png')
```

**Bug**
The bug is due to an invalid file name. In general, filenames like `path:some:thing.png` are not valid, two `:` are not allowed in windows. However, `path:something.png` with only one `:` works just fine.

**How to fix**
On line 1169 in `/core/predictor.py`, the variable `save_figs` cannot contain 2 `:`.

BR, Sophia

**Comment by smousavi05** [comment]
Thank you very much @ConstantinGahr. Yes, unfortunately the package does not work under the windows yet but as you mentioned it is only due to minor issues like naming and path convention differences between the os and windows. It should be easy to fix all these issues by just following the error comments and it would be great if you could send your fixes through pull requests so other people could use it as well.

**Comment by smousavi05** [comment]
@ConstantinGahr I have already applied your suggested fixes to the code. It would be great if you could reinstall EqT and let me know if the new version works under Windows or not?

**Comment by ConstantinGahr** [comment]
@smousavi05 Thank you for your quick reply. It seems to work without a problem!

**Comment by Anirudh366** [comment]
> Referen
Used the instruction 
conda create -n eqt python=3.7

conda activate eqt

conda install -c smousavi05 eqtransformer 

Hello @smousavi05 , Facing the same issue , can you share the updated version link/instruction for windows.

**Comment by smousavi05** [comment]
@Anirudh366 it is difficult to advise a solution without more info on the error. An alternative would be to use the Seisbench implementation of EQT in PyTorch.
