### ISSUE TITLE
class_weight option in model.fit_generator

### ISSUE THREAD

**Issue by alirezaniki** [smousavi05/EQTransformer#127]
Dear @smousavi05 

Recently, I've faced a problem running EQT training.py code. The issue arises from the class_weight option in the model.fit_generator which is by default set to {0: 0.11, 1: 0.89}. The error (which originates from the TF version) asks me to replace the keys (0 and 1) with "detector", "picker_P", and "picker_S".
As there are 3 classes in EQT, my question is that what classes do the keys 0 and 1 refer to? 

Thank you in advance,
Alireza.

**Comment by alirezaniki** [comment]
Dear @smousavi05 
My apologies for mixing the questions, but I am facing some weird usage of memory while training my dataset (It's only a ~6 Gb hdf5 file and a 16 Mb metadata file). Have you ever faced such a thing? It's occupying more and more memory after each epoch.

![Screenshot from 2022-04-23 17-26-55](https://user-images.githubusercontent.com/24492517/164945963-e0d55e25-2535-49df-ae62-feba1237e864.png)

**Comment by smousavi05** [comment]
No, that is not Normal. I never had that problem before

**Comment by alirezaniki** [comment]
Thank you for your response

**Comment by Chouyuhin** [comment]
> Thank you for your response

Hello，
I have the same problem with you , did you figure it out?
Lokking forward to your reply.
If necessary，my email is chouyuhin777@163.com

Thanks!
