### ISSUE TITLE
About station_list.json

### ISSUE THREAD

**Issue by xunen63** [smousavi05/EQTransformer#13]
Thanks a lot for your model!

There is no stationListFromMseed in hdf5_maker as the documation says in the detection examples.
Maybe it should be the code as you say in  https://eqtransformer.readthedocs.io/en/latest/tutorial.html#downloading-continuous-data  from EQTransformer.utils.downloader import makeStationList ?

**Comment by smousavi05** [comment]
stationListFromMseed currently is only available when you install the EQTransformer from Github source. 
One thing you can do now is to take the EQTransformer/utils/downloader from Github and replace it with the downloader.py in your root (where you have installed EQT) or reinstall the whole package directly from Github.  
I'll add this module to the pip and anaconda version in a few weeks.
