### ISSUE TITLE
Conda installation issues

### ISSUE THREAD

**Issue by ktagen-sudo** [smousavi05/EQTransformer#131]
Hi I am running into an error message when trying to install the package with conda:

` Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/smousavi05/linux-64/current_repodata.json`

Did you mean:

`https://conda.anaconda.org/smirarab/linux-64/repodata.json` ?

Also, when trying to install it with python I get the following error:

```
 File "/opt/spack/opt/spack/linux-centos7-haswell/gcc-10.2.0/python-3.9.12-246uxetzvhguenowcodryp3rmthkqzv3/lib/python3.9/zipfile.py", line 1438, in getinfo
    raise KeyError(
KeyError: "There is no item named 'nbconvert/tests/exporter_entrypoint/eptest-0.1.dist-info/WHEEL' in the archive"
```

I was able to install it successfully with pip though

**Comment by smousavi05** [comment]
@ktagen-sudo please try installing it using either Pip or directly from GitHub. 
The GitHub version is more recent.

**Comment by ktagen-sudo** [comment]
Thank you @smousavi05! I installed it with `pip install EQTransformer -U`
