### ISSUE TITLE
Bi LSTM residual. 

### ISSUE THREAD

**Issue by Erik-BM** [smousavi05/EQTransformer#134]
At https://github.com/smousavi05/EQTransformer/blob/01bf112a00c1a3bbb43adb2c7dba3e21b5fbcdb9/EQTransformer/core/EqT_utils.py#L2596 
you claim it is a residual block, but it is not. What is correct here?

**Comment by smousavi05** [comment]
@Erik-BM this is a specific type of residual block called network-in-network block.

**Comment by Erik-BM** [comment]
@smousavi05 ok, thank you for the clarification. Closing this.
