### ISSUE TITLE
Modifications needed in Eqt_Utils.py file?

### ISSUE THREAD

**Issue by alirezaniki** [smousavi05/EQTransformer#136]
Dear @smousavi05 

I may be wrong with this but apparently, it seems there's a typo in line 921 of EqT_utils.py:

if sst and (sst-20 >= 0) and (sst-20 < self.dim):
should be:
if sst and (sst-20 >= 0) and (sst+20 < self.dim)
??

**Comment by smousavi05** [comment]
@alirezaniki right, it seems they should be +20. Although it is hard to believe that I left such an obvious thing and there might be a reason for that, I have changed it in the code. 
Thanks for pointing it out.
