### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by zhong-yy** [smousavi05/EQTransformer#137]
As is mentioned in #97, the the file naming format is `NETWORK.STATION.LOCATION.CHANNEL__STARTTIMESTAMP__ENDTIMESTAMP.mseed`. I am still confused about the name requirement.

(1) Can I put different channels at the same station into one mseed file?
(2) Do  traces in different channels at the same staion have to share the same name except for the `CHANNEL` part, even if traces at different channels have different starttime and endtime?
(3) In the filename, are `STARTTIMESTAMP` and `ENDTIMESTAMP` important? I found that I could still run the example after I changed the ENDTIMESTAMP and ENDTIMESTAMP to a arbitrary time.

**Comment by smousavi05** [comment]
@zhong-yy 
1) yes you can put the different channels in one messed file
2) I think no.
3) not really, maybe only in the association part

Anyway if you look at some downloaded examples from IRIS I think you'll get the answer to most of your questions.

**Comment by zhong-yy** [comment]
Thank you for you answer
