### ISSUE TITLE
Difference between original model and conservative model?

### ISSUE THREAD

**Issue by JoshRichW** [smousavi05/EQTransformer#138]
Could you add some documentation explaining the difference between the original model and the conservative model in ModelsAndSampleData?

The difference in level of detection between the two is quite remarkable, and I'd be interested to know part of what causes that.

Also thanks for sharing the code and models for EQTransformer, it is much appreciated.

**Comment by smousavi05** [comment]
@JoshRichW There is not much difference between the two models regarding the network architecture (only 1 or 2 layers). The main difference comes from the training procedure and the hyperparameters used for data augmentation. So if you are interested in maximizing the number of detections and are not concerned about the false positive rates (which you can remove in association and location steps), you should use the original model with higher threshold values. In contrast, if you care about only detecting true events, the conservative model (with much lower threshold levels) suits you better.

**Comment by smousavi05** [comment]
@JoshRichW well there is no general rule for hyperparameter tuning. It highly depends on the characteristics of your data, how the model performed initially on it, and what issues you are trying to address/improve.

**Comment by JoshRichW** [comment]
Ok, thank you for the information
