### ISSUE TITLE
EQTransformer version in pypi

### ISSUE THREAD

**Issue by ecastillot** [smousavi05/EQTransformer#146]
Hi dear Mostafa,

Could you please update the project in pypi? 
When I install EQTransformer using pip, it installs the version 0.1.59. Unfortunately the requirements using this version are very old (example tensorflow==2.0.0). According to this repository, there is already version 0.1.61 with more compatible requirements for other projects. It is also useful to install EQTransformer in colab using pip.

Thank you,
Emmanuel

**Comment by smousavi05** [comment]
Please use the version on the GitHub repo which is the most up-to-date one.
