### ISSUE TITLE
issue about multiple GPUs

### ISSUE THREAD

**Issue by Chouyuhin** [smousavi05/EQTransformer#149]
hi,mousavi,
first, thanks to EQTransformer!
I got an issue : I use eqt on my own dataset without changing model structure or training code
But when I run the code on multiple GPUs, the usage on every GPU is so low, and the time of one epoch is more  than  using one gpu,
<img width="605" alt="image" src="https://user-images.githubusercontent.com/99780523/227934970-188d9d55-b0af-496a-90aa-6ab8a8c50da1.png">
can you give any suggestion please?

**Comment by smousavi05** [comment]
As I mentioned before, this is due to the data reading and pre-processing that prevent taking full advantage of multiple GPU
