### ISSUE TITLE
OSError: SavedModel file does not exist at: ../ModelsAndSampleData/EqT_original_model.h5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by Pengling2022** [smousavi05/EQTransformer#155]
Hello, 
I have this error when running the sample code, how should I solve it?

thank you very much！

**Comment by ayunriaainun** [comment]
Hello, I am also facing the same problem. Have you found a way to resolve it?

Thank you

**Comment by Pengling2022** [comment]
Hi,

I had solved this problem.
you can change the model path and other path with your computer local path. It's best that the path is complete.


such as:
'D:\EQTransformer\ModelsAndSampleData\EqT_model_conservative.h5'


best wishes!


| |
pengling2022
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/11/2024 23:44 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
State ***@***.***> |
| Subject | Re: [smousavi05/EQTransformer] OSError: SavedModel file does not exist at: ../ModelsAndSampleData/EqT_original_model.h5/{saved_model.pbtxt|saved_model.pb} (Issue #155) |

Hello, I am also facing the same problem. Have you found a way to resolve it?

Thank you

**Comment by ayunriaainun** [comment]
Thank you for your help, it's perfectly successful now.
