### ISSUE TITLE
Paper question: how to get f1-score from STA/LTA and AIC methods?

### ISSUE THREAD

**Issue by ErrorOverflow** [smousavi05/EQTransformer#17]
I'm glad that you have shared this perfect paper. But there are something confusing me. Classical method always give 3 single prediction point. How can I transform these prediction points to f1-score?
![捕获](https://user-images.githubusercontent.com/32595386/96414967-6eacbd80-1220-11eb-9644-51977d1c665e.JPG)

**Comment by smousavi05** [comment]
for STA/LTA is easy you just calculate the false positive, true positive, and false-negative rates (based on correctly and wrongly detected events), then calculate Precision and Recall and using them F1 score (see the supplementary information of the paper). 
For the pickers like AIC, we considered picks within +- 0.5 seconds of the true pick (ground truth) as true positives. I hope this helps.
