### ISSUE TITLE
H5PY 2.10.0 dependency

### ISSUE THREAD

**Issue by SquirrelKnight** [smousavi05/EQTransformer#25]
Hello,

I wanted to mention that I encountered a recent dependency issue when running a fresh install of eqt via the Conda method. While the latest version of h5py was installed, it appears that it does not work with the provided model. In order to get everything working, I had to uninstall h5py and run the command 'conda install h5py=2.10.0'.

Additionally, it appears that the current version of eqt does not contain the latest updates to the preprocessor module that allow for the specification of the 'preproc_dir'.

-Sincerely, Jesse

**Comment by smousavi05** [comment]
Hi Jesse, @SquirrelKnight 

Thanks for the comment I am aware of these just haven't had time to pull the latest version to pip and anaconda. However, you can get the latest version through GitHub. 

Regards, 
Mostafa

**Comment by SquirrelKnight** [comment]
Hi Mostafa,

Thank you for the response! I’ve got everything working well now.

-Sincerely, Jesse

**Comment by bvicic** [comment]
I still have the problem with h5py. I installed eqtransformer on our HPC cluster from github after creating a fresh environment with conda. when i run python setup.py install i get this error:
error: h5py 3.1.0 is installed but h5py~=2.10.0 is required by {'tensorflow'}

I checked what version I have, and when i import h5py in python, it says its version 2.10.0

any ideas what I should do?

**Comment by bvicic** [comment]
if someone has the same problem:
h5py was installed under pipy.

this helped:

python -m pip uninstall h5py
pip install h5py==2.10.0

**Comment by smousavi05** [comment]
yes, this is due to the new update in tensorflow which just works with h5py 2.10.0
