### ISSUE TITLE
how to apply EQTransformer tool  for picking P and S phases of the local events(< 150 km)

### ISSUE THREAD

**Issue by geophysics91** [smousavi05/EQTransformer#3]
Thanks for the nice tool. I want to know one thing, can this model and tool be applicable directly for local events (P and S) picking  (< 150km ) of a certain area of India or china. if not let me also know what steps should i follow for the same.

**Comment by smousavi05** [comment]
Hi, this is exactly what the code has been designed for. You can directly apply it for detecting and picking P and S in local distances (< 200 km). All you need is to install the package and use a pre-trained model (in ModelsAndSampleData directory). Your data need to be in SAC or Miniseed format (preferably in day-long files) with a conventional file name format (see the documentation).

**Comment by geophysics91** [comment]
Thanks, However my data are in mseed format with hourly files(in one day 24 number of files/channel) ....can you please suggest some scripts for merging the 24 nos hourly files into single day-long file.
secondly, if i have data gaps in between 24 hours how to overcome this problem...does it require to fill zero.

**Comment by smousavi05** [comment]
Hourly files are fine. You don't need to merge them. Just make sure the name formats of the file follow the one in the documentation. 
EQTransformer takes care of all the pre-processing including the gap filling. All you need is to give the code the address of the directory containing your mseed files (mseed files for each station in a separate folder). 
I suggest you run the jupyter notebooks in the examples directory. It tasks about 30 min to run all the examples and it makes everything clear.

**Comment by geophysics91** [comment]
ok...my data format is in this format RT.RET.00.BHE__2018-01-01T01:00:00.005000Z__2018-01-01T01:59:59.995000Z.mseed can it be read by your programme or needs to change ?? However, i was trying to change this format as per the documents file but while slicing there is problem 'UTCDateTime object is not subsciptible..so can you please suggest a solution for the same.
