### ISSUE TITLE
What's the difference btween the two models in "ModelsAndSampleData"?

### ISSUE THREAD

**Issue by hycarbon** [smousavi05/EQTransformer#31]
Hello,

I noticed you upload a new model file EqT_model2.h5. Could you say something a little bit about the difference between these two models?

Thanks.

**Comment by smousavi05** [comment]
@hycarbon these are models trained with different augmentation settings so they behave differently. Eqt_model2.h5 might result in a higher probability values in general- and as a result relatively higher detections-but might result in higher false positive rate as well.

**Comment by hycarbon** [comment]
Thanks. I will test them on my datasets.
