### ISSUE TITLE
TypeError in Downloading Continuous Data in Tutorial

### ISSUE THREAD

**Issue by Bryanrt-geophys** [smousavi05/EQTransformer#34]
Hello Mostafa,

I am currently trying out your code while running:
MacOS Catalina==10.15.7 
python==3.7.9
tensorflow==1.14.0
keras==2.3.1

When I come to the first part of the tutorial to import makeStationList I get this warning:

`from EQTransformer.utils.downloader import makeStationList
Using TensorFlow backend.`

If I continue to attempt to use makeStationList, this error occurs:

```
makeStationList(client_list=["SCEDC"], 
                min_lat=35.50,
                max_lat=35.60, 
                min_lon=-117.80, 
                max_lon=-117.40, 
                start_time="2019-09-01 00:00:00.00", 
                end_time="2019-09-03 00:00:00.00", 
                channel_list=["HH[ZNE]", "HH[Z21]", "BH[ZNE]"],
                filter_network=["SY"],
                filter_station=[])
Traceback (most recent call last):

  File "<ipython-input-2-0a8c305af80c>", line 10, in <module>
    filter_station=[])

TypeError: makeStationList() missing 1 required positional argument: 'json_path'
```

Any suggestions? Thanks for your time and assistance.

**Comment by Bryanrt-geophys** [comment]
Looking at makeStationList(), it looks like the first argument needed by the function the the 'json_path'. This path to the data, is it precooked into eqtransformer and used for the tutorial? I would assume that this is where I would normally provide my own path to data, if I had my own data at this point. Is that correct?

**Comment by smousavi05** [comment]
@Bryanrt-geophys 
Hi Bryan,
That is correct. Apparently the tutorial on the documentation page was a bit outdated. I updated it. 
You can also run the jupyter notebooks in the example folder (those are more complete and with more details). 
BTW version 1.59 is up as well. I tested it with both tensorflow 1.14 and 2.0.0 and looks fine.

**Comment by Bryanrt-geophys** [comment]
Thanks, that seemed to work perfectly. I upgraded to EQTransformer==0.1.59 and tensorflow==2.0.0. It looks like h5py still needs to be downgraded to continue, but so far so good. Thanks for the prompt and helpful directions.
