### ISSUE TITLE
small display message bug in hdf5_maker.py

### ISSUE THREAD

**Issue by MrXiaoXiao** [smousavi05/EQTransformer#4]
In hdf5_maker.py line 75.

https://github.com/smousavi05/EQTransformer/blob/2061c8b882e6c1c8040e1588f69c5841e1068fdb/EQTransformer/utils/hdf5_maker.py#L73-L79

The variable 'mseed_dir' in print function should be 'save_dir', otherwise the display message could be misleading.

By the way, I tested your method on some seismic data we are studying, and the results are very nice. Thanks for sharing!

**Comment by smousavi05** [comment]
Thanks for the bug report, I'll fix it. 
Glad that you find EqT useful in your research.
