### ISSUE TITLE
associator sqlite3 error

### ISSUE THREAD

**Issue by dylanmikesell** [smousavi05/EQTransformer#40]
Hi! Thanks for this awesome code. I had it up and running with my data in 30 minutes. Incredibly easy compared to other ML detection tools I have tried using in the past 6 months.

I have run into one error though when trying run the associator. Running on linux with Python 3.7.9. I installed EQT using anaconda.

When running the associator with the following: 

```
  import shutil
  import os
  from EQTransformer.utils.associator import run_associator

  out_dir="association"
  try:
      shutil.rmtree(out_dir)
  except Exception:
      pass
  os.makedirs(out_dir)

  run_associator(input_dir="detections", 
      start_time="2020-03-31 00:00:00.00", 
      end_time="2020-04-03 00:00:00.00", 
      moving_window=15, 
      pair_n=3,
      output_dir=out_dir,
      consider_combination=False)
```

I get this error.

```
Traceback (most recent call last):
  File "main.py", line 120, in <module>
    consider_combination=False)
  File "/home/dylanmikesell/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/utils/associator.py", line 106, in run_associator
    )''')
sqlite3.OperationalError: database is locked
```

Is the associator looking for a sqlite DB? If so, is there some step I am missing to create this DB? I cannot find anything about it in the docs. This error on line 106 also doesn't make sense given the code on github, so I wonder if the version I installed via conda is old. Thoughts?

Thanks!

**Comment by dylanmikesell** [comment]
Update: Reinstalled EQTransformer from the git repo. New error makes sense given associator.py that is in the repo.

```
Traceback (most recent call last):
  File "main.py", line 120, in <module>
    consider_combination=False)
  File "/home/dylanmikesell/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer-0.1.59-py3.7.egg/EQTransformer/utils/associator.py", line 108, in run_associator
    )''')
sqlite3.OperationalError: database is locked
```
Still curious what this error is caused by and how to get rid of it.
Thanks!

**Comment by dylanmikesell** [comment]
This is perhaps not a EQTransformer issue. I found this [thread](https://stackoverflow.com/questions/2740806/python-sqlite-database-is-locked).

And testing item 4, I get
```
$ sqlite3 cache.db ".backup cache.db.bak"
Error: database is locked
```
I tried the suggestions, but still have a locked DB and cannot get the associator to run.

**Comment by smousavi05** [comment]
Hi @dylanmikesell and thanks for the message.
This is a new bug, we haven't had this before. The trace back is for the initial step of generating an empty db. This perhaps has something to do with your os and sqlite version on your machine. Do you get the same error if you just run the examples on the jupyter notebooks? You can also do a simple test and on a separate folder or environment try to import sqlite3 and generate a database:
    if os.path.exists("phase_dataset"):
        os.remove("phase_dataset")
    conn = sqlite3.connect("phase_dataset")
    cur = conn.cursor()
    
    cur.execute('''
        CREATE TABLE phase_dataset (traceID TEXT, 
                                    network TEXT,
                                    station TEXT,
                                    instrument_type TEXT,
                                    stlat NUMERIC, 
                                    stlon NUMERIC, 
                                    stelv NUMERIC,                        
                                    event_start_time DateTime, 
                                    event_end_time DateTime, 
                                    detection_prob NUMERIC, 
                                    detection_unc NUMERIC, 
                                    p_arrival_time DateTime, 
                                    p_prob NUMERIC, 
                                    p_unc NUMERIC, 
                                    p_snr NUMERIC,
                                    s_arrival_time DateTime, 
                                    s_prob NUMERIC, 
                                    s_unc NUMERIC, 
                                    s_snr NUMERIC,
                                    amp NUMERIC
                                    )''')
# you can then read in the table you generated into a pandas dataframe
conn = sqlite3.connect("phase_dataset")
tbl = pd.read_sql_query("SELECT * FROM phase_dataset", conn);

**Comment by dylanmikesell** [comment]
Thanks for the suggestion! I just ran a test on my mac with your minimal example here. That works just fine and I can see the column headers in tbl. It must be to do with the linux cluster I am running on. I cannot get the minimum working example to run on that machine. I get the same error about the db being locked. I will report back once I talk our admin and get it figured out. I am not sure it is an EQTrasnformer issue at this point.

**Comment by dylanmikesell** [comment]
This is not a bug. This was an issue with permission on a remote cfis disk share.
