### ISSUE TITLE
Bug when loading the model

### ISSUE THREAD

**Issue by wangliang1989** [smousavi05/EQTransformer#46]
````bash
============================================================================
Running EqTransformer  0.1.59
 *** Loading the model ...
[1]    70227 killed     python makejson.py
````

the makejson.py is below:
````python
import os
import sys
from EQTransformer.utils.hdf5_maker import stationListFromMseed # 生成台站列表
from EQTransformer.utils.hdf5_maker import preprocessor # 数据转化
from EQTransformer.core.predictor import predictor # 识别信号

mon = '201612'

model = '/Users/liang/work/eqt/EQTransformer/ModelsAndSampleData/EqT_model.h5'
locations = {
    "BBSX": [30.32824, 103.04621,  840.5], "BCPC": [30.94832, 103.31643, 1347.0],
    "BFSC": [30.59908, 103.18747, 1350.0], "BHGC": [30.12775, 103.16326,  776.0],
    "BHLC": [30.51558, 103.42745,  570.0], "BHPC": [30.55102, 102.94482, 1651.0],
    "BJFC": [30.01914, 103.02261,  666.0], "BJHC": [30.60857, 103.58865,  540.0],
    "BLHC": [29.71326, 103.24694,  646.0], "BLSC": [30.28700, 103.29210,  615.0],
    "BLXC": [30.17515, 102.92073,  700.4], "BQFC": [30.68795, 102.74354, 2153.0],
    "BQYC": [30.46657, 103.14805, 1195.3], "BRLZ": [30.99886, 102.79512, 3376.2],
    "BTLG": [30.93672, 103.50188, 1186.0], "BWLZ": [31.02935, 103.17649, 2019.0],
    "BWQC": [30.76124, 103.66290,  601.0], "BWTB": [30.72967, 103.43284,  885.0],
    "BXFC": [30.48838, 102.70589, 1277.0], "BXSC": [30.38091, 102.80905, 1182.0],
    "BYFC": [30.79711, 103.23357, 1546.0], "BYKC": [30.49259, 103.08265, 1631.0],
    "BYQC": [30.58943, 103.30350,  800.0],
}
mdays = [
    '01', '02', '03', '04', '05', '06', '07', '08', '09', '10',
    '11', '12', '13', '14', '15', '16', '17', '18', '19', '20',
    '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31'
]

for mday in mdays:
    workdir = mon + mday
    if os.path.exists(workdir) :
        print(workdir, "生成台站列表")
        stationListFromMseed(workdir, locations)
        print(workdir, "数据转化")
        preprocessor(
            preproc_dir = "preproc", mseed_dir = workdir,
            stations_json = 'station_list.json', overlap = 0.3, n_processor = 2
        )
        print(workdir, "识别信号")
        predictor(
            input_dir = workdir + '_processed_hdfs', input_model = model,
            output_dir = 'detections', detection_threshold = 0.1,
            P_threshold = 0.1, S_threshold = 0.1,
            number_of_plots = 100, plot_mode = 'time'
        )
        os.chdir('/Users/liang/work/eqt/gap')
        os.rename('detections', workdir + '_detections')
        print(workdir, "删除临时文件")
        os.system('rm -rf ' + workdir + '_processed_hdfs preproc')
        os.system('rm -rf ' + workdir)
````

**Comment by smousavi05** [comment]
is this happen when you try the examples as well?

**Comment by wangliang1989** [comment]
I saw your message immediately. However, I did not reply immediately because I need to complete the ongoing test before I can reply to you.

The bug doesn't happen when tring the examples.

You can see the script I showed above. I think this script is easy to understand. My data structure is: one day's data is in a folder. Each time this script is run, it will process one month of data. There is a loop structure in this script, and each loop processes one day's data. When the cycle reaches the seventh day, the bug will appear. When I run this script to process the data on the 7th day of each month, the bug appears. Then I re-run the script from the 7th day data. At this time, when the script processed the data on the 13th of this month, the bug appeared again. Similarly, on the 19th, 25th, and 31st, bugs will always appear. Other days will not appear.

Thank you

**Comment by smousavi05** [comment]
@wangliang1989 okay. Lets track the problem more closely. 1) could you check to see if the data on those days have a specific similarity? especially when the data length in a miniseed is too short (~< 1 hour)? or has long gaps? 2) I do see that in each loop you first perform the pre-processing and then running the prediction for that day. The problem with this approach is that each time that you run the prediction function it upload the model and the error you are getting is more likely due tensorflow and this repeated frequent loading and unloading of the model. So I suggest instead to first preprocess all of your data and put them in a single directory and then run the prediction at the end on all the data. This will make the running much faster as well as the model loading is the most time consuming part. Moreover, I see that you do not use the uncertainty estimation. So then using mseed_predictor and direct running it on a single folder containing all of your miniseed file might be even a better option. Mseed_predictor one is more appropriate when you have many data and it will save lots of space as it does not require saving of the pre-processed data. Let me know if you had other questions.

**Comment by wangliang1989** [comment]
1) I think I don't have this problem because I have fill up the gaps with zero.
2) You mean uploading the model repeated frequently may produce errors? I don't know what the "uncertainty estimation" you said is.

Thanks!

**Comment by smousavi05** [comment]
Right each time you call the prediction function it loads the model and this problem occurs.

**Comment by wangliang1989** [comment]
OK. But what is the uncertainty estimation? You mean the detection_uncertainty in the csv files? But, we already have the detection_probability.

**Comment by smousavi05** [comment]
Uncertainties are the standard deviation of those probabilities. At each run the output probabilities can vary and the uncertainty estimates reflect this variation. Anyway this option is only available on prediction module and not in mseed_predictor @wangliang1989

**Comment by wangliang1989** [comment]
long time no see！

My data processing has been completed. I'm already doing the next step of my research. Generally speaking, I think the results form EQT are accurate, better than human, but there are some obvious mistakes.

If I can do anything to help improve this program, I would be happy, including sharing some data with you.

**Comment by smousavi05** [comment]
Thanks @wangliang1989 It would be good if you could just share the EqT plots for those cased that you think EqT did a mistake. This would help us to learn about the issues and problems and improve the model in the future.

**Comment by wangliang1989** [comment]
OK, I will open new issue to give you these plots to report bugs.
Good bye
