### ISSUE TITLE
Increasing memory consumption when running on MSEED files

### ISSUE THREAD

**Issue by maratumba** [smousavi05/EQTransformer#5]
I'm running the model on my MSEED files that consist of 1 month of data, 33 stations. Using `mseed_predictor` with CPU, around station 8, the process gets killed. During the run, I watched the system resources and the memory consumption just keeps increasing and when it's full, the process crashes.

Running on Ubuntu 20.04

**Comment by smousavi05** [comment]
to run mseed_predictor on miniseeds of 1 month long you need at least 16 GM of RAM. Otherwise either break your mseed files to smaller chunks (e.g. 10 days or less) or run the hdf_maker and predictor if you have enough storage for pre-processed data.

**Comment by maratumba** [comment]
I have 32GB of RAM and 32GB swap space. I ended up breaking 33 stations into 8 chunks. If I iterate over these chunks in python by calling `mseed_predictor` for each chunk, it still consumes all the memory and crashes. I had to iterate over these chunks with a bash script, only then the memory was released after each chunk. 

So it seems like there is a memory leak in `mseed_predictor`. It is possible to work around it as I did or as you suggested but if there's an easy fix, it would make things much easier.

**Comment by smousavi05** [comment]
That is kind of strang. What is the sampling rate of your data? one place that the code could take too much memory is in the resampling part (especially when the data has very low -40 or 20 Hz- or very high -1000 Hz sampling rate). In this case, resampling your data in advance might help. 

The code itself does not keep too many things in memory. What I am suspicious about the most is the TensorFlow itself. Some versions of it have this issue that does not release the cache and you need to manually release the memory or restart the terminal. You might learn more about this is TensorFlow forums. I don't know if they have fixed it in the newer versions. So maybe upgrading or downgrading to a specific version of TF helps.

**Comment by maratumba** [comment]
Sampling rate is 100Hz. I'll look into TF pages. Thanks!

**Comment by Chouyuhin** [comment]
Hello,
I have the same issue with you ,did you fix it up?
looking forward to your reply
sincerely
