### ISSUE TITLE
Unable to download data from IRIS

### ISSUE THREAD

**Issue by tonino0013** [smousavi05/EQTransformer#50]
Dear Developers,
I wanted to test the examples with my stations that are shared at IRIS, however I am not able to download the data.
Here are the parts of the code:

```
#First Part
from EQTransformer.utils.downloader import makeStationList
from EQTransformer.utils.downloader import downloadMseeds
import os
```
result First Part-->OK

```
#Second Part
json_basepath = os.path.join(os.getcwd(),"json/station_list.json")
print(json_basepath)

makeStationList(json_path=json_basepath,
                client_list=["IRIS"], min_lat= -23.41, max_lat=-9.29, min_lon=-69.81, 
                max_lon=-57.24, start_time="2021-02-01 00:00:00.00",
                end_time="2021-02-01 03:00:00.00", channel_list=["BH[ZNE]", "SH[Z]"],
                filter_network=["1U", "C", "C1", "GE","IU", "SY","XX"], filter_station=[])
```
result SecondPart --> OK

```
#ThirdPart
downloadMseeds(client_list=["IRIS"], stations_json=json_basepath, 
               output_dir="/home/tonino/EQTransformer/downloads_mseeds", 
               start_time="2021-02-01 00:00:00.00",
               end_time="2021-02-01 03:00:00.00", min_lat=-23.41, max_lat=-9.29,
               min_lon=-69.81, max_lon=-57.24, chunk_size=1,
               channel_list=["BH[ZNE]", "SH[Z]", "EH[ZNE]"], n_processor=1
```
resultsThirdPart --> half OK.

```
[2021-02-24 21:23:10,483] - obspy.clients.fdsn.mass_downloader - INFO: Initializing FDSN client(s) for IRIS.
[2021-02-24 21:23:10,491] - obspy.clients.fdsn.mass_downloader - INFO: Successfully initialized 1 client(s): IRIS.

####### There are 3 stations in the list. #######
======= Working on REDDE station.
======= Working on SOEP station.
======= Working on LPAZ station.
```
It seems ok, however the data is not stored at downloads_mseeds folder, it keeps empty. I tested with a simple obspy script and the data is available.
Thank you in advance.
Tonino

**Comment by smousavi05** [comment]
downloader module in EqT is actually a wrapper on Obspy fdsn. So if you are able to download them using obspy, it should work as well in EqT. Anyway, no mater how you download your mseed files the code should be able to perform subsequent processes.

**Comment by tonino0013** [comment]
Dear @smousavi05, thanks for the answer. So, I can also put my off-line data?, Does the data must the IRIS naming structure?, Does the data need to be all channels the same length (1 hour for example?), is there a folder structure for the off-line data?
Thanks in advance
Tonino

**Comment by smousavi05** [comment]
@tonino0013 Yes you can use your off-line data. Your miniseed files just need to have IRIS naming format. No, the data can be different lengths, they should not be too short though (the total length of data in a single miniseed file should not be shorter than 30 min). You just need to put your station info in a 'station_list.json' file and pass it to the prediction module along with the address to the folder containing your miniseed files. 
Good Luck

**Comment by tonino0013** [comment]
Dear @smousavi05 ok, thank you for the answers
