### ISSUE TITLE
Detection error: First station works well second station shows error. 

### ISSUE THREAD

**Issue by MAcosta-GitHub** [smousavi05/EQTransformer#51]
Hi, when running detections (from seeds directly) the first station in my seeds directory works well then I get the following error (I am using a very similar code as the one in the example detections.ipynb). 

> 02-26 08:43 [INFO] [EQTransformer] Finished the prediction in: 0 hours and 5 minutes and 49.27 seconds.
> 02-26 08:43 [INFO] [EQTransformer] *** Detected: 364 events.
> 02-26 08:43 [INFO] [EQTransformer]  *** Wrote the results into --> " /Users/acosta/EQTransformer-master/examples/detections2/B057_outputs "

> 02-26 08:43 [INFO] [EQTransformer] Started working on B921, 2 out of 53 ...
> 02-26 08:43 [INFO] [EQTransformer] 20190901T000000Z__20190902T000000Z.mseed

> KeyError                                  Traceback (most recent call last)
> /Users/acosta/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/core/mseed_predictor.py in _mseed2nparry(args, matching, time_slots, comp_types, st_name)
>     447         meta["instrument_type"]=st[0].stats.channel[:2]
> --> 448         meta["network_code"]=stations_[st[0].stats.station]['network']
>     449         meta["receiver_latitude"]=stations_[st[0].stats.station]['coords'][0]
> 
> KeyError: 'B921'
> 
> During handling of the above exception, another exception occurred:
> 
> KeyError                                  Traceback (most recent call last)
> <ipython-input-7-74501aa3bac4> in <module>()
>      14          overlap=0.3,
>      15          gpuid=None,
> ---> 16          gpu_limit=None) 
> 
> /Users/acosta/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/core/mseed_predictor.py in mseed_predictor(input_dir, input_model, stations_json, output_dir, detection_threshold, P_threshold, S_threshold, number_of_plots, plot_mode, loss_weights, loss_types, normalization_mode, batch_size, overlap, gpuid, gpu_limit, overwrite)
>     302             eqt_logger.info(f"{month}")
>     303             matching = [s for s in file_list if month in s]
> --> 304             meta, time_slots, comp_types, data_set = _mseed2nparry(args, matching, time_slots, comp_types, st)
>     305 
>     306             params_pred = {'batch_size': args['batch_size'],
> 
> /Users/acosta/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/core/mseed_predictor.py in _mseed2nparry(args, matching, time_slots, comp_types, st_name)
>     452     except Exception:
>     453         meta["receiver_code"]=st_name
> --> 454         meta["instrument_type"]=stations_[st_name]['channels'][0][:2]
>     455         meta["network_code"]=stations_[st_name]['network']
>     456         meta["receiver_latitude"]=stations_[st_name]['coords'][0]
> 
> KeyError: 'B921'

I don't understand where this comes from since the two station messed files were downloaded in the same way and I have the exact same channels for both of them.

**Comment by smousavi05** [comment]
@MAcosta-GitHub it seems there is an inconsistency in the miniseed files. Could you check the miniseed file (for statin B921) using Obspy to see if all the fields for stream are written out?
