### ISSUE TITLE
mseedpredictor systematically do not picks anything during the last 40 minutes of dayly .mseed file

### ISSUE THREAD

**Issue by Luchorigami** [smousavi05/EQTransformer#56]
Hello,

I'm trying to run EQT on several 1day-long .mseed files with mseed_predictor and it seems that i have an issue:

After the picking, when I plot the P-S picks over the raw data it seems that there is systematically a gap of picks during the last 40 min of the trace. (i.e from 23H20min). I'm running EQT over a lot of 1-day long .mseed file and all present the same final gap of picks...
  
Moreover, it seems that changing the overlap value in the input of the mseed_predictor function make the length of this gap change...

Can you help me on that ? I tried to check deeper on the code but i did not find anything resolving this issue.
Tell me if you need more infos.

Best,
Luc

Note: I checked that there were effectively actually events 'potentially pickable' during the last 40 min of .mseed files.

**Comment by smousavi05** [comment]
@Luchorigami   could you send me one the plot and mseed file for one of those days that you think there are some events on the last 40 min ?

**Comment by Luchorigami** [comment]
Hi thank you for your response,

Here is a plot for a day (23-04-2017) where we can easily see the final gap of picks. Vertical line are picks, red for P and blue for S.
![EQTpicksentireday](https://user-images.githubusercontent.com/75418735/111961628-923aa380-8af1-11eb-8fa7-fe8d353b4bc7.png)
![EQTpickszoomend](https://user-images.githubusercontent.com/75418735/111961633-92d33a00-8af1-11eb-8380-04ba09b3302b.png)


(For the plot only:) Seismic traces amplitudes are not consistent over time in the plot because I  have normalized each segment of 15 min by it's maximum amplitude to help the visualization of small event when large event occurs during the day. 

The related 1 day long .mseed file is: 
[C1.MT01..HH.zip](https://github.com/smousavi05/EQTransformer/files/6180658/C1.MT01.HH.zip)

I'm running EQT over 4 month of data, here is also the EQT output phase file that include this particular day (The station is MT01). There is no picks later than 23:20 over all the days tested.
[X_prediction_results.txt](https://github.com/smousavi05/EQTransformer/files/6180607/X_prediction_results.txt)

**Comment by smousavi05** [comment]
HI Luc,

Thanks for sending your plots over. You detected many events. For the gap
at the and of the trace: what I think is that it might be due to the batch
size. Setting up the default value (batch_size = 500) means that if the
remaining part of the data divided into 1 min pieces (including the overlap
value among them) are less than 500, no prediction will be done. So an easy
test would be just to reduce the batch size and check the detection result
at the end of the traces. However, check the overall number of detected
events too as changing the batch size might change the overall number of
detections. Let me know if this helps.

Regards,
Mostafa

**Comment by Luchorigami** [comment]
Hi and thank you,

I changed the batch value and it seems to work fine. However, I needed to choose a very low value (ie. batch_size<=5) to make the gap disappear. 
In the help of the function mseed_predictor you suggest to use a value between 200 and 1000. Do you think it can cause problems to use 5 or 1 for the batch_size (I'm not really sure that i understand how this variable works) ? Is it only for speed ?

Also I notice that using a strong overlap value increase the number of detection more than changing the batch_size.

Anyway, thanks for your help and for sharing this code,
Luc

**Comment by smousavi05** [comment]
5 would be too low. It can change the result is not just about the speed. I
recommend working with a combination of lower batch size and higher overlap
to make sure all the data length has been covered.

**Comment by smousavi05** [comment]
Another easy solution might be to just add 240000 zeros to the end of each
trace in your mseed files  .
