### ISSUE TITLE
Downloading MSEED data

### ISSUE THREAD

**Issue by Cthuulhaa** [smousavi05/EQTransformer#57]
Hello,

I have just installed EQTransformer and tested the example in the tutorial, which has worked as expected. However, when I try to download MSEED data in a different time period it doesn't work. For example, after

`from EQTransformer.utils.downloader import downloadMseeds`

if I try

`downloadMseeds(client_list=["SCEDC", "IRIS"], stations_json='station_list.json', output_dir="downloads_mseeds", min_lat=35.50, max_lat=35.60, min_lon=-117.80, max_lon=-117.40, start_time="2019-03-01 00:00:00.00", end_time="2019-03-01 05:00:00.00", chunk_size=1, channel_list=[], n_processor=2)`

the output is

`####### There are 1 stations in the list. #######`
`[2021-03-22 19:53:54,130] - obspy.clients.fdsn.mass_downloader - INFO: Initializing FDSN client(s) for SCEDC, IRIS.`
`[2021-03-22 19:53:54,139] - obspy.clients.fdsn.mass_downloader - INFO: Successfully initialized 2 client(s): SCEDC, IRIS.`
`======= Working on B921 station.`

and no MSEED data is downloaded. Is there a step in between that I am missing?

All the best,
Catalina

**Comment by Cthuulhaa** [comment]
It seems it has to do with the chunk_size parameter. What would be the best way to define this parameter for my 5-hours example?

Best,
Catalina

**Comment by smousavi05** [comment]
@Cthuulhaa this downloader module works for the mseed files of larger than 1 day. This constraint is to avoid frequent data request to the data centers that usually causes problems. You can either download longer duration (> 1 day) data and filter out the results to your time period of interest or download the mseed file using obspy directly.

**Comment by Cthuulhaa** [comment]
@smousavi05 Oh, I had managed to download 5 hours of data before your answer, but I will keep what you say in mind and download the MSEED files using ObsPy. Is this problem with the data request valid for all the clients/networks?

**Comment by smousavi05** [comment]
It’s just happened sometimes when you ask for many small data that keep
sending too many requests to IRIS and their system automatically ignore the
request from your IP.

**Comment by Cthuulhaa** [comment]
I see. Thank you for your answers. I am closing this issue!

**Comment by LuYijing1** [comment]
> @smousavi05 哦,我已经下载5小时的数据在你的答案之前,但我会记住你所说的和下载使用ObsPy mse文件。 这个问题与所有客户的数据请求有效/网络吗?

Hi, how did you download your mseed?  Is it using the code given by the author and do the filename need to have formatting requirements?
