### ISSUE TITLE
When the detection threshold is not ideally set

### ISSUE THREAD

**Issue by Cthuulhaa** [smousavi05/EQTransformer#58]
Hi,

 I suppose this is what happens when the you don't set the detection threshold properly: the S-wave arrival was not picked, although it is pretty clear on the horizontal components.

I find the figure quite illustrative for those who are learning to use EQTransformer.

![2021-02-10 01:44:18 157500](https://user-images.githubusercontent.com/81183635/113284183-8d43d400-92e9-11eb-8892-bb4f7465ab89.png)

Cheers!

**Comment by smousavi05** [comment]
@Cthuulhaa that is correct. Currently the EqT has been set to only declare the picks when they are with the beginning and end of the detection window. In this example, although S probability is high, it occurs where the detection probability is pretty low and this is why it has not been picked. You can either lower the detection threshold or modify the conditional probability constrain.
