### ISSUE TITLE
trainer h5 used in predictor() returning error: Cannot create group in read-only mode.

### ISSUE THREAD

**Issue by Bryanrt-geophys** [smousavi05/EQTransformer#60]
Hello Mustafa,

I have pretty well finished up the R package to take by-hand picked phase arrival data sets and convert them into h5 files to load into eqtransformer.core.predictor. When I do a side-by-side comparison of my output h5 file, [https://gitlab.com/Bryanrt-geophys/sac2eqtransformr/-/tree/master/sample_data/Training_h5](url), to the 100samples.hdf5 in your provided sample data set I don't see any structural differences aside from my objects being 1x6000 rather than 3x6000. This is because sensors only recorded single component data over the time period I am building my sample set from. Is this an issue? If so is there an order that the components are to be listed in the rows of the objects (i.e. HHZ row 1, HHE row 2, HHN row 3)? When I try to use my retraining model, I receive the error: `Cannot create group in read-only mode`. I am assuming this is an issue with how I built/closed my hdf5 file. Would you have any advice on how to go about fixing this? 

The package still has some minor bugs before it's fully functional but here is the function that takes tidied data and creates the h5 file, [https://gitlab.com/Bryanrt-geophys/sac2eqtransformr/-/blob/master/R/make_trainer_hdf5.R](url). I know your work has been in Python and this is R, but I assume the ideas of how you create an h5 should look extremely similar.

**Comment by Bryanrt-geophys** [comment]
Hmmm... I just noticed that the links I provided do not seem to work unless you copy and paste them into your browser.... not sure if that a GitHub -> GitLab problem. Sorry about that.

**Comment by Bryanrt-geophys** [comment]
Okay, I apologize, I have been sitting in front of the computer for too long because I am making lots of simple mistakes. I am passing my h5 file to the wrong function. I should be using EQTransformer.core.trainer(). I will make that adjustment now, however, I am still curious if the single component data making a 1x6000 object in the data is acceptable or if it must be 3x6000. If so, do you recommend I load two rows of NA values or 0's?

**Comment by smousavi05** [comment]
I am not sure if I got it!

**Comment by Bryanrt-geophys** [comment]
Did the links I provided work for you?

So I have created an h5 file to pass to EQTransformer.core.trainer(). All of the stations I have collected mseed values from are single component and thus the _EV objects in the h5 are 1x6000, rather than the 3x6000 in the provided tutorial data. In EQTransformer.core.trainer() there is the variable input_dimention which defaults to (6000,3). I don't know if I can just adjust this value to (6000,1) and it would be okay or if I need to edit my NMTSO_trainer.h5 file to have 3x6000 shaped objects. I hope that made more sense that my last few rambling posts. 

Lastly, I think I may have a package dependency problem again, when I run EQTransformer.core.trainer() I receive the fallowing error:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-11-6036285ff312>", line 22, in <module>
    use_multiprocessing=True)

  File "/Users/jolante/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/core/trainer.py", line 356, in trainer
    history, model, start_training, end_training, save_dir, save_models, training_size, validation_size=train(args)

  File "/Users/jolante/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/EQTransformer/core/trainer.py", line 325, in train
    class_weight={0: 0.11, 1: 0.89})

  File "/Users/jolante/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

  File "/Users/jolante/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)

  File "/Users/jolante/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/engine/training_generator.py", line 185, in fit_generator
    generator_output = next(output_generator)

  File "/Users/jolante/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/utils/data_utils.py", line 625, in get
    six.reraise(*sys.exc_info())

  File "/Users/jolante/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value

  File "/Users/jolante/opt/anaconda3/envs/eqt/lib/python3.7/site-packages/keras/utils/data_utils.py", line 610, in get
    inputs = future.get(timeout=30)

  File "/Users/jolante/opt/anaconda3/envs/eqt/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value

AttributeError: 'NoneType' object has no attribute 'attrs'
```

As always, thanks for all of your help! If it wold be more helpful for me to show you my data and resultant problem just let me know. Thanks!

Bryan

**Comment by smousavi05** [comment]
@Bryanrt-geophys Hi Bryan, yes you need fill the empty (not available) components with zeros. However, please note that the components need to come in a specific order. This means for instance if you only have the Z component, you need to make a 3*6000 array in which the first two rows are zeros.

**Comment by Bryanrt-geophys** [comment]
Awesome! Thank you @smousavi05 for the guidance. I am assuming the first row would be the N component, second is E, and it sounds like Z is the last component. Is that right?

**Comment by smousavi05** [comment]
@Bryanrt-geophys No, it should be E, N, Z

**Comment by Bryanrt-geophys** [comment]
Thank you! I imagine that should solve my problem running the trainer function. I'll have it tested by tomorrow afternoon.

**Comment by Bryanrt-geophys** [comment]
@smousavi05

So, I edited my code to take into account the channel and make 3x6000 objects in the data group in the .h5 file I am passing to the trainer function and the function now runs just fine. However, When I pass the final_model.h5 output from trainer function to the predictor function, no events are found at any station. Could this be a result of variable values chosen in the EqT functions, the quality of the data I used, or does it sound like I may still have an error in the way my training data is formatted? I imagine that if it was a variable issue or an issue with my sample size, sample quality, etc. that I would have few detections or bad detections rather than none at all. Would you be willing to look at my training h5?

I realized I linked the URL's wrong in the above posts so here is a working link to my [h5 file](https://gitlab.com/Bryanrt-geophys/sac2eqtransformr/-/blob/master/sample_data/NMTSO_trainer.h5). 

Thanks for your time!
Bryan

**Comment by smousavi05** [comment]
@Bryanrt-geophys It could be due to many things. Building a new model is not easy. So first you need to make sure that the training has been done correctly. Some of the useful things that you can look at are the learning curves and output report of the training process. Moreover, could you tell me how many events do you have in your training set?

**Comment by Bryanrt-geophys** [comment]
I don't think the training was done correctly because the first graphical
output from trainer is empty (I'm at front it now but I think the title had
_f1 in this graphs name).The second graph that shows learning over epochs,
though I really don't understand the graph, all curves drop to zero after
the first epoch and that doesn't seem right to me.

I also just remembered that I changed the data in each objects from a
1x6000 but I did not change the snr_db attribute to have 3 values, so that
may be my error. As I am not a native Python programmer I have a question
on your syntax. Looking at the exemplary attribute CSV file,
100_samples.csv, the snr_db column had three values encompassed in double
brackets. Are those double brackets necessary to include? I believe there
was one other column also bracketed, so I'll bracket both of necessary.

I used two days of data from 20 stations for training and ended up with 349
events. I then ran the predictions function on the same dates of data to
see if I would pick up the same events I trained the model on. I think this
is the same idea you covered in your tester function, right? Forgive my
slow learning, but I think ground truth is the data used to train, right?

As always, thanks for your time and assistance.

Bryan

**Comment by smousavi05** [comment]
@Bryanrt-geophys don't worry Bryan, what you are trying to do is not trivial and all these are totally normal. It will take some times and you just need to be patient. 
 the close brackets ( [ ] ) in which elements are separated by comma ( , ) represent "lists". So you should pay attention to closely follow the structure. 
First thing to do is to make sure all the format and data structure in your training set are correct,  so you need some ways for testing. 
Second, you need to make sure the problem does not come from your data characteristics. So a good practice is to start training will all the augmentation flags turned off, and after that you make the training run normally (based on curves and reports) you can turn on the flags one by one. 
Third, your training data are too small to fully train the full network. One easy fix is to just append your data into the STEAD and retraining the whole the EqT. This might just be a bit time consuming. The second option, is to fix the pre-train weights on most of the layers except the last one or two layers and then just use your data (this is what transfer learning).

**Comment by Bryanrt-geophys** [comment]
Thanks for the great instructions once again. I was curious how large of a training sample I would need to work and how large was too large. After going back to your paper it looks like you trained EqT on STEAD which was in the M's of samples and most other methods use 100's k to M's of samples too. Is that the range of samples I would want to try to use? I have seven years of cataloged attribute data available. Paired with the mseed download function from EqT and my R code I can potentially append my h5 training set as much as needed. My original thought process was to test two days worth of data and continue to randomly sample from my seven years and append it to my original training set until results started to plateau. Unfortunately using my code to wrangle these attributes files and mseed files fills up my RAM fairly quickly so I am restricted to running a few days worth at a time to create the h5's once an h5 is made though I think the compression rate should make appending it pretty reasonable. I am hoping to retrofit my code with an R version of Dask (at least I think Dask is the Python equivalent), to help chunk my data and lower the computation costs.

I will be sure to make sure the data structure in the attributes and csv file match perfectly to what was demonstrated. Thank you for pointing out the lists, in R you can easily define lists but they are not printed in brackets. I will first test loading the h5 with a regular R list and then manually add brackets to see if the r structure translates or not. 

In the two options you suggested, appending my data to STEAD or to fic the pre-train weights, I did not fully understand the second suggestion. What do you mean by layers? Are you suggesting I set a singular value for all p_weight and s_weight values aside from a few samples in my own data set or append my data to STEAD, fix the p_weight and s_weight of STEAD to a singular, higher value and then allow my data weights to vary?

**Comment by Bryanrt-geophys** [comment]
Also, what is the class of the coda_end_sample object? In the CSV file, it is in double brackets with an internal period ( i.e. [[ 4920.]] ).

**Comment by smousavi05** [comment]
to train the EqT you need at least 100'sK of samples. However, now you just need to work out on your current data to make it work as the sample training set in the EqT does. Then you can scale it up. 

Don't worry about the second option (transfer learning). It is more complicated than that and some other changes need to be done on the EqT side. 

double bracket can be a list of list with float number. But you don't need coda_end_sample field as it is not being used in the training. So now just focus on finding the bug and just make the training run normally.

**Comment by Bryanrt-geophys** [comment]
Hello @smousavi05,

Sorry this has been open for so long. I have been overtaken by finals and am just getting back to my efforts to apply your work. I have been exploring some of the flags in the trainer() function and using the generated loss and f1 figures to diagnose my attempts. So far, all of my f1 scores have been a flatline on zero which leads me to assume I have issues with my data formatting in the h5 file I am passing to trainer(). 

I need to put a lot more time into learning Python, but I put some side by side python chunks into an Rmarkdown file using {h5py} to show the format of my h5 file and the exemplary h5 file provided with {EqT} to try to help me find the point where I am going wrong.  I created my h5 file using an R package for writing hdfs but I hadn't looked at the output in python until now.

Here are the lines of comparing the attributes 'snr_db', 'network_code', and 'back_azimuth_deg' (chosen for the fact that they appear to represent each of the different data formats in the attributes):
```
# my file
group['CBET.SC_20200902051800_EV'].attrs['snr_db']

# your file
group2['109C.TA_20060723155859_EV'].attrs['snr_db']

# my file
group['CBET.SC_20200902051800_EV'].attrs['network_code']

# your file
group2['109C.TA_20060723155859_EV'].attrs['network_code']

# my file
group['CBET.SC_20200902051800_EV'].attrs['back_azimuth_deg']

# your file
group2['109C.TA_20060723155859_EV'].attrs['back_azimuth_deg']
```

Here are the outpus:
```
# my snr_db
array([array([0.       , 0.       , 3.1094018])], dtype=object)

# your snr_db
array([56.79999924, 55.40000153, 47.40000153])

# my network_code
array([b'SC'], dtype=object)

# your network_code
'TA'

# my back_azimuth_deg
array([186.])

# your back_azimuth_deg
159.3
```

With my limited knowledge on Python, I am assuming the structure of my attributes are not the same as yours. Does that assumption seem correct to you? If so, I am going to put some time into experimenting with moving my data objects into a Python format using R's reticulate package and write the hdfs with h5py rather than creating the hdfs with hdf5r in R. 

Bryan

**Comment by smousavi05** [comment]
@Bryanrt-geophys There are definitely some formatting issues. However, it is hard to narrow it down this way as I never used R to make a hdf5 file.

**Comment by Bryanrt-geophys** [comment]
No problem, I may try transferring my data frame I populated the h5 file from into python via R's version of the feather package and try making the H5 via h5py.

Similarly, I have noticed in each attempt to make a trainer model I receiver warnings in the early calculation that graphs failed to be evaluated topologically and my f1 scores are always zero. Does this indicate any other issues? 

I will go back to the code you provided me for creating an h5 file and try using that for my transferred data and see if I can make progress there.

Thanks for your time and help!
Bryan

**Comment by smousavi05** [comment]
that just means the training is not done and if it stay the same after many epochs it means it leans nothing.

**Comment by smousavi05** [comment]
Hey @Bryanrt-geophys I came a cross this [package](https://maihao14.github.io/QuakeLabeler/) that could create the training dataset for EqT.

**Comment by Bryanrt-geophys** [comment]
Thanks Mustafa! This looks super helpful for my project.

By the way, do you know if there is a way to continue a model trainer that is terminated partway through? I have the top Google Colab account I can have and it only allows me 24hrs runtime. When using the data set I have merged with one of the chunks of STEAD data sets available, I only get through about 60 epochs out of the 200 I am trying to reach before my session times out. It would be great if I could continue the trainer building in a new session.

**Comment by smousavi05** [comment]
I haven't done that but I know it is possible by doing some modification to
the TF model fitting setting within the code. It calls "fine tuning" means
the training is resumed by continouning updating the previous weights.
