### ISSUE TITLE
False negatives

### ISSUE THREAD

**Issue by Cthuulhaa** [smousavi05/EQTransformer#62]
Hi,

do you see any false negative on these stations? It is a mining explosion (ML 1.1), with data available for 6 stations, but the event was detected on only one. Most of the traces look noisy, but I think I do "see something" on some of them (e.g. on station WIMM), but I am not an expert at detecting events...

Cheers!

![ge falks](https://user-images.githubusercontent.com/81183635/114911288-26f99e00-9e1f-11eb-81c7-6d9ec47111b0.png)
![ge flt1](https://user-images.githubusercontent.com/81183635/114911329-31b43300-9e1f-11eb-90a6-ec4660d5ce19.png)
![sx muhb](https://user-images.githubusercontent.com/81183635/114911342-34af2380-9e1f-11eb-951f-3541c250cf51.png)
![sx neub](https://user-images.githubusercontent.com/81183635/114911352-3842aa80-9e1f-11eb-8d3e-838948666b07.png)
![sx wimm](https://user-images.githubusercontent.com/81183635/114911368-3bd63180-9e1f-11eb-848f-8f2a53f379ba.png)
![th bonn](https://user-images.githubusercontent.com/81183635/114911379-3ed12200-9e1f-11eb-9b35-8cc2728c54e4.png)

**Comment by smousavi05** [comment]
@Cthuulhaa Hi
I do see a weak signal on FLT1. The one on WIMM can be an event as well but this station look like to be a short period one, is that correct? that might be a reason for not picking it up. You may want to try the other model available here or/and try the prediction module with uncertainty estimation on.

**Comment by Cthuulhaa** [comment]
Hi!
Yes, these are all HH* channels. What is the difference between both models?

**Comment by smousavi05** [comment]
the second model has less false negatives but with a cost of possible false positives. So you need to use higher threshold values to reduce false positives if you got many.
