### ISSUE TITLE
TF version requirements

### ISSUE THREAD

**Issue by mdenolle** [smousavi05/EQTransformer#63]
Hi Moustafa,

I am having issues installing with pip and source code because the TF version 2.0.0 does not for on my Mac

Reading https://pypi.org/simple/tensorflow/
No local packages or working download links found for tensorflow==2.0.0
error: Could not find suitable distribution for Requirement.parse('tensorflow==2.0.0')

Here are my TF installations:

tensorboard               2.5.0                    pypi_0    pypi
tensorboard-data-server   0.6.0                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.4.1                    pypi_0    pypi
tensorflow-estimator      2.4.0                    pypi_0    pypi

I use python 3.8.5

I read [online](https://github.com/tensorflow/tensorflow/issues/39621) that older versions of tf2.2 require an older version of python (3.5, 3.6 or 3.7). 
Would it be okay to update the requirements for a later version of tf?
Cheers,
m.

**Comment by smousavi05** [comment]
@mdenolle 

Hi Marine, 
Python version is the main issue. Updating the tf to a later version won't fix the issue as it is very likely that other required packages result in a similar issue. 
While updating the whole code and dependencies to be compatible with python 3.8 would be a long-term fix, downgrading the python version would be a faster solution. Could you try it on another machine or cloud?

Regards, 
Mostafa

**Comment by mdenolle** [comment]
OK sounds good! Thank you for this. I am trying to use it in class, so we have a mix of institutional hubs, clouds, personal laptop, colab etc.. might as well stick to the quick and safe fix.
