### ISSUE TITLE
problem with event association

### ISSUE THREAD

**Issue by saeedsltm** [smousavi05/EQTransformer#64]
Dear @smousavi05 

I have a problem with "moving_window" parameter in event association. I started setting it to 10s and i found some picks arrives within first 10th second of a minute will not be associated to an event. For example, the following are rows from Y2000.pha describing an event:

2018 811144614.3629 6.36 51 7.56 5.000.00
KOLO BP  HHE     2018 8111446 0.00       12.87ES 0
KOLO BP  HHZ IP 02018 811144610.33        0.00   0
DLRM BP  HHE     2018 8111446 0.00       14.17ES 0
DLRM BP  HHZ IP 02018 811144610.85        0.00   0
TOLS BP  HHE     2018 8111446 0.00       16.03ES 0
TOLS BP  HHZ IP 12018 811144611.94        0.00   0
ABTL BP  HHE     2018 8111446 0.00       20.41ES 0
ABTL BP  HHZ IP 02018 811144614.28        0.00   0
SHIF BP  HHE     2018 8111446 0.00       21.85ES 1
SHIF BP  HHZ IP 02018 811144615.04        0.00   0
NOKA BP  HHE     2018 8111446 0.00       23.20ES 0
NOKA BP  HHZ IP 02018 811144615.98        0.00   0

since there were some stations absent, i've decided to check "X_prediction_results.csv" inside "detection" folder for those stations which not associated to that event. The following are rows according to that event which were not associated:

KHIA_BP_BH_2018-08-11T14:45:30.000000Z | BP | KHIA | BH | 28.861 | 51.181 | 48 | 2018-08-11 14:46:09.960000 | 2018-08-11 14:46:15.460000 | 0.99 | 2018-08-11 14:46:10 | 0.79 | 43 | 2018-08-11 14:46:12.250000 | 0.85 | 11.5
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

JNAK_BP_BH_2018-08-11T14:45:30.000000Z | BP | JNAK | BH | 28.879 | 51.69 | 16 | 2018-08-11 14:46:09.320000 | 2018-08-11 14:46:13.680000 | 0.99 | 2018-08-11 14:46:09.320000 | 0.84 | 41.3 | 2018-08-11 14:46:11.170000 | 0.79 | 9.7
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

While the above picks have high probability for detection, p and s picks, but not associated to the event. One solution would be  increasing the  "moving_window" parameter but i don't think that could guarantee for subsequent events and phases where lie around (let say) 15 seconds and so on!

**Comment by smousavi05** [comment]
@saeedsltm Hi Saeed, 
Thanks for sharing this. If I remember correctly the association is done based on the detection time (the time associated with the first sample point with detection probability above the threshold level) which can be different than the P arrival time. this is to make it possible including those stations with only S arrivals into the associated event. Anyway, I need to take a closer look into this to double check. Give me some time as I am currently busy with some other things. Meanwhile, I recommend using a larger window. The window length depends on the intensity of the seismicity (how frequently events show up after each others) and the spacing between the stations. 10 seconds seems too narrow to me.

**Comment by saeedsltm** [comment]
Dear @smousavi05 
Thanks so mush. So, I will play around with it, till you back.
