### ISSUE TITLE
plot_helicorder if mseed contains gap

### ISSUE THREAD

**Issue by saeedsltm** [smousavi05/EQTransformer#65]
Dear @smousavi05 

In case our data (mseed file) has time gap, the plot_helicorder function does not show the whole stream since it plots only the first trace of stream:
[Line 68 of file plot.py]
`st[0].plot(type='dayplot', color=['k'],interval=60, events=event_list, outfile=input_mseed.split("\\")[-1].split('.mseed')[0]+'.png')`
I would suggest using "st" instead of "st[0]" because each time we call the "plot_helicorder", we pass one mseed file as an argument, so the final plot shows the whole stream including all gaps if exists.

Regards

**Comment by smousavi05** [comment]
thanks for sharing this, I'll look at it. @saeedsltm
