### ISSUE TITLE
AttributeError from Tensorflow issues?

### ISSUE THREAD

**Issue by amfintel** [smousavi05/EQTransformer#69]
Everything was working fine up until a few day ago. It appears there is some issue with the 2.0.0 version of TensorFlow possibly? I noticed the bot pull request with an update to Tensorflow 2.5.0. I can no longer get the code to run. 

This is the exact error I am getting and I have made no changes to the code since it worked last. 
![image](https://user-images.githubusercontent.com/81640771/119585856-6dc4a700-bd80-11eb-9ff9-67203da3923e.png)

**Comment by smousavi05** [comment]
@amfintel did you update your tensorflow or python version?

**Comment by amfintel** [comment]
I am working with this through Google Colab so it does not run on my local system. 

I use `!pip install git+https://github.com/smousavi05/EQTransformer`
to access EQTransformer and when I do this it uninstalls Tensor 2.5.0 and install 2.0.0

This is the end of the output from installing with the above command. 
> Successfully installed EQTransformer-0.1.59 SecretStorage-3.3.1 cryptography-3.4.7 gast-0.2.2 h5py-2.10.0 jeepney-0.6.0 keras-2.3.1 keras-applications-1.0.8 keyring-23.0.1 pkginfo-1.7.0 tensorboard-2.0.2 tensorflow-2.0.0 tensorflow-estimator-2.0.1 tqdm-4.48.0

If I reinstall the newest version of tensorflow I get these warning errors as an output
>ERROR: eqtransformer 0.1.59 has requirement h5py==2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: eqtransformer 0.1.59 has requirement tensorflow==2.0.0, but you'll have tensorflow 2.5.0 which is incompatible.`

And this is the new error that I get when trying to run the utils.downloader
![image](https://user-images.githubusercontent.com/81640771/119882133-e8a5d300-bee2-11eb-913e-14d8c13e3d87.png)


I've gone into the generic_utils.py and manually added the missing attribute/functions. Then I have no issues with the stations downloader or the downloadMseeds but I run into issues with mseeds_predictor.

**Comment by smousavi05** [comment]
I see, there are some changes in TF 2.5 that require me to go over the code and fix the conflicts. Let me see if I can find some times to do so.

**Comment by smousavi05** [comment]
@amfintel It should work now, just try to reinstall EqT from the github page.

**Comment by amfintel** [comment]
It's working wonderfully again! Thanks for the quick fix.

**Comment by Bryanrt-geophys** [comment]
Hello @amfintel,

I am also trying to run EQT over Colab, but I am new to using Colab and running into a few issues. May I speak with you about how you were able to get it up and running?

Bryan
