### ISSUE TITLE
new encoding, dependency bugs in install

### ISSUE THREAD

**Issue by filefolder** [smousavi05/EQTransformer#73]
Hi, was having encoding troubles installing the current (0.1.61) version on a new machine. Pip would crash. 

Tracked it down to an encoding issue in setup.py. Somehow that file got some strange encoding in it, but explicitly setting it back to utf-8 works. 

`with open("README.md", "r", encoding='utf-8') as fh:`

I also noticed that the h5py dependency is off; needs to be 3.1.0 to be compatible with tf2.5. Looking forward to being able to update my dependencies again!

**Comment by filefolder** [comment]
follow-up, seems like 1.61 does not work as-is? When training, there's an issue with how loss_weights are used and also I suspect something with setting up the various attention settings / SeqSelfAttention. Can anyone confirm or is this just on my end?

**Comment by smousavi05** [comment]
@filefolder version 0.1.61 is only available from GitHub at the moment. Using pip you will get the stable version (0.1.59). I have updated the h5py version in the setup.py but need more info for encoding error. Could you please share the full error message?

Do you get the error with 1.61 only for the Trainer? were you able to run other modules and examples?

**Comment by filefolder** [comment]
The encoding glitch appears to be fixed now,  or maybe it was occurring only on a particular machine. There was some sort of incompatible byte somewhere in the README.md file. 

I will report the other trainer etc problems in detail in a separate report.

**Comment by filefolder** [comment]
Ah ok, still an issue on the python 3.6 machine but not on my python 3.8 machine

```
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-h4niztu8/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-h4niztu8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lrx11_hg
         cwd: /tmp/pip-req-build-h4niztu8/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-h4niztu8/setup.py", line 4, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1994: ordinal not in range(128)
```
