### ISSUE TITLE
Version of Tensorflow and Keras

### ISSUE THREAD

**Issue by Cthuulhaa** [smousavi05/EQTransformer#78]
Dear Mostafa,

it is explicitly mentioned in the installation instructions that Python 3.6 or 3.7 will be needed to run EQTransformer. I have found that it can also be run in Python 3.8, but I ignore if this can lead to some kind of issue/problem.

Are there any requirements for the version of Tensorflow and Keras? Newer version produce much faster detections than older ones.

Cheers!

**Comment by smousavi05** [comment]
@Cthuulhaa  Interesting, which version of EQT are you using? there is no python version restriction for Tensorflow or Keras I was more worried for Obspy and other packages.

**Comment by Cthuulhaa** [comment]
@smousavi05 it is version 0.1.58.

Cheers!

**Comment by smousavi05** [comment]
@Cthuulhaa Thanks
