### ISSUE TITLE
numpy requirement

### ISSUE THREAD

**Issue by dylanmikesell** [smousavi05/EQTransformer#80]
When installing obspy in a new conda Python=3.7 environment, you end up with numpy=.1.20.3. However, tensorflow requires numpy~=1.19.2. I noticed in setup.py that there is not requirement for numpy. Should that be added?

install_requires=[
	'pytest', 
	'keyring>=15.1', 
	'pkginfo>=1.4.2',
	'scipy==1.4.1', 
	'tensorflow==2.5.0', 
	'keras==2.3.1', 
	'matplotlib', 
	'pandas',
	'tqdm==4.48.0', 
	'h5py==3.1.0', 
	'obspy',
	'jupyter'],

**Comment by smousavi05** [comment]
thanks for the comment. Well, tensorflow and obspy download their own numpy version. Not sure if this cause a problem but will add this to th the setup requirement.

**Comment by dylanmikesell** [comment]
Missing == in the updated code. This raises an error. Will send a pull request for this in a bit.
