### ISSUE TITLE
Is this normalization intended?

### ISSUE THREAD

**Issue by Syler1984** [smousavi05/EQTransformer#86]
I've been going through mseed_predictor code because I am curious about the preprocessing methods it employs. And I noticed that the _normalize method applies a normalization by a maximum amplitude rather than the maximum absolute value:

https://github.com/smousavi05/EQTransformer/blob/af2e2e4843e5ac11396095d5828e95d16b68ed17/EQTransformer/core/mseed_predictor.py#L533
 
```
max_data = np.max(data, axis=0, keepdims=True)
```

rather than, for example:

```
max_data = np.max(np.abs(data, axis=0))
```

Is this intended behaviour?

**Comment by smousavi05** [comment]
@Syler1984 that is true and it is fine as this is the standard deviation is the one actually used.
