### ISSUE TITLE
GPU ID in Google Colab

### ISSUE THREAD

**Issue by Bryanrt-geophys** [smousavi05/EQTransformer#89]
Hello again @smousavi05,

I have just started to experiment with merging my built training data  set with one of the partitions of STEAD. The large increase in training size has prompted me to move the project to Google Colab. 

Thus far I have only used CPU's to run the trainer function. Could you explain a bit on what is required by the gpuid variable called for in the trainer function? Is there a line of code I am supposed to run in Colab to get specs about the available gpu's and input the name as the gpuid? Thanks so much for your assistance!

Bryan

**Comment by smousavi05** [comment]
Hi Bryan @Bryanrt-geophys, I don't think that you need to specify the gpu# when using Colab. leaving it as default should be fine. That parameter is mainly for using on local GPU clusters when the number of GPUs is limited and you prefer to work with an specific one.

**Comment by Bryanrt-geophys** [comment]
Awesome, that makes things easier on my end. Thanks for the prompt response!

**Comment by Bryanrt-geophys** [comment]
So I tried running the trainer function in Colab while leaving the values of `gpuid` as `None`. Upon doing so, the runtime for a single epoch of a data set with 225k events and batch size of 200 is ~4.5 hrs. 

After a few minutes I get a note from colab letting me know that I have my runtime set to use GPU's but none are being used. I am guessing this means that I need to specify information in the `gpuid` variable. I have no idea what kind of information EQT wants for that variable though. 

Running `!nvidia-smi` in Colab returns:
```
Fri Sep 10 18:10:49 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P0    27W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
and running `!nvidia-sm -L` yeilds:
```
GPU 0: Tesla P100-PCIE-16GB (UUID: GPU-54a8cf2d-e48c-8e1e-5158-28a050af705e)
```

Is anthing from the above GPU info what I should put into `gpuid`?

Here is how I currently have the function set up and it seems to work fine outside of it using the CPU's rather than the GPU's. Thanks for all of the help.
```
trainer(input_hdf5='/content/gdrive/MyDrive/NMTSO_data/chunk_zip/merged.hdf5',
        input_csv='/content/gdrive/MyDrive/NMTSO_data/chunk_zip/merged.csv',
        output_name='NMTSO_EQT_merge1_gaussian',
        input_dimention=(6000, 3),
        cnn_blocks=5,
        lstm_blocks=2,
        padding='same', 
        activation='relu',
        drop_rate=0.4,
        shuffle=True,
        label_type='gaussian', 
        normalization_mode='std',
        augmentation=False,
        add_event_r=0.6, 
        shift_event_r=0.99, 
        add_noise_r=0.3,
        drop_channel_r=0.5, 
        add_gap_r=0.2, 
        scale_amplitude_r=None,
        pre_emphasis=False, 
        loss_weights=[0.05, 0.40, 0.55], 
        loss_types=['binary_crossentropy', 'binary_crossentropy', 'binary_crossentropy'], 
        train_valid_test_split=[0.60, 0.20, 0.20], 
        mode='generator', 
        batch_size=200, 
        epochs=200, 
        monitor='val_loss', 
        patience=12,
        gpuid=None, 
        gpu_limit=None,
        use_multiprocessing=True)
```

**Comment by smousavi05** [comment]
@Bryanrt-geophys "GPU 0: Tesla P100-PCIE-16GB (UUID: GPU-54a8cf2d-e48c-8e1e-5158-28a050af705e)
" is the info for the GPU 0 in your colab setting. 0 is the gpuid that you can use in your EqT run command.

**Comment by Bryanrt-geophys** [comment]
Awesome! Thank you so much. Can I leave `gpu_limit=None`?

**Comment by smousavi05** [comment]
@Bryanrt-geophys yes you can. That is just to let others use the GPU as well when you are working on a shared cluster.

**Comment by smousavi05** [comment]
I think this can be closed now
