### ISSUE TITLE
Issues installing the package via Conda

### ISSUE THREAD

**Issue by 8844-43** [smousavi05/EQTransformer#90]
When I was trying to install the package using `conda install -c smousavi05 eqtransformer`, the error message shown below occurred. 

python version in the eqt environment is 3.7, trued python=2.7, python=3.8 but they didn't solve the problem.

![Issues installing EQTransformer](https://user-images.githubusercontent.com/66616277/133362002-802f521d-d01b-441f-bda7-782272afa138.jpg)

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

**Comment by chinu739** [comment]
How did you solve it?

**Comment by Saneesh-Ali** [comment]
How did you solve it?

**Comment by 8844-43** [comment]
How did I solve it?
1. Try `pip install EQTransformer`. Got some error saying "EQTransformer=0.1.59 requires scipy=1.4.1
2. Try `pip list`. Noticed that my scipy version is 1.7.1. 
3. Use `conda install scipy=1.4.1` to downgrade the scipy package. 
4. Try `pip install EQTransformer` again. Successful!

**Comment by Saneesh-Ali** [comment]
Thank you, I also solved it by `pip install EQTransformer`
