### ISSUE TITLE
Using different filter range than the training dataset

### ISSUE THREAD

**Issue by hasbishiddiqi** [smousavi05/EQTransformer#92]
Hi @smousavi05,

I notice that in mseed_predictor, a band pass filter is apllied to the waveforms (1 - 45 Hz). I guess this is because the training dataset was also filtered in this frequency range.

I have some noisy stations with high frequency noise. The signal become clearer if I filter it with lower frequency raange (for example: max frequency 1-10 Hz or 1-15 Hz). So I modified the filter range in the mseed_predictor, and I got more picks from these noisy stations. I use the EqT_model.h5 training model.

Do you think this is OK or this can cause some issues?

Thanks!

Hasbi

**Comment by smousavi05** [comment]
@hasbishiddiqi Hi Hasbi, that is perfectly fine as you have just narrowed the frequency band. This is totally okay and should not make any problem.

**Comment by hasbishiddiqi** [comment]
@smousavi05 Thank you!
