### ISSUE TITLE
Compatibility issue between Tensorflow 2.x and Numpy 1.20

### ISSUE THREAD

**Issue by alirezaniki** [smousavi05/EQTransformer#99]
Hi there,

I am trying to install the EQTransformer package on a Compute Canada Machine (Siku) but the example codes run into errors cause of compatibility issues between Tensorflow 2.5 and Numpy 1.20 (https://github.com/tensorflow/tensorflow/issues). I tried to reinstall the Numpy and used different versions of it but at some other points, it fails again.
I also asked the CC support team for help and they said that the requirement needed in EQTransformer is not a working configuration of programs.
Any suggestions for an optimal configuration to resolve the issue?

**Comment by smousavi05** [comment]
@alirezaniki I haven't try that so don't know

**Comment by ostueker** [comment]
The install_requirements in `setup.py` are clearly broken.

```
	'numpy==1.20.3',
	'keyring>=15.1', 
	'pkginfo>=1.4.2',
	'scipy==1.4.1', 
	'tensorflow==2.5.2', 
```

Tensorflow 2.5.2 is incompatible with numpy==1.20.3 and support for numpy>=1.20.x has only been added in TensorFlow 2.7.0.

I also recommend not pinning exact versions, but rather defining minimum and/or maximum versions.

**Comment by smousavi05** [comment]
thanks Oliver

**Comment by ostueker** [comment]
I've opened a PR.
